server:
    port: 8080

spring:
    application:
        name:test-tassk
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.h2.Driver
        url: "jdbc:h2:mem:embp_test_collection;\
            INIT=CREATE SCHEMA IF NOT EXISTS embp_test_collection\\;
            SET SCHEMA embp_test_collection"
jpa:
    show-sql: true
    properties:
        hibernate:
            default_schema: embp_test_collection
            jdbc:
                lob:
                    non_contextual_creation: true
            dialect: org.hibernate.dialect.H2Dialect

logging:
    level:
        ROOT: INFO
        org.springframework: WARN
        ru.ramazanov.TestTask: INFO



list_files: 1.txt, 2.txt
default_path: ./files-text/